[build]
  command = "npm ci && npm run build -- --configuration production"
  publish = "dist/jsw"
  environment = { NODE_VERSION = "20", NPM_VERSION = "10" }

# Redirects for Angular routing (SPA support)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
